### ISSUE TITLE
Build A Website

### ISSUE THREAD

**Issue by devarshishimpi** [devarshishimpi/Elite-Bot#17]
Build A Website for the Bot

**Comment by TheDeveloperRyan** [comment]
I am not the best at frontend web dev but I can try to help =)

**Comment by devarshishimpi** [comment]
Okay

**Comment by lilmistake** [comment]
I'll be down as well 🖐️

**Comment by devarshishimpi** [comment]
Okay

**Comment by daniel-dev-lab** [comment]
I could also help with the development, as I see things I can fix and / or improve :)  Love the project by the way!

**Comment by devarshishimpi** [comment]
> I could also help with the development, as I see things I can fix and / or improve :)  Love the project by the way!

Sure
