### ISSUE TITLE
Make bot more flexible with interactions

### ISSUE THREAD

**Issue by TheDeveloperRyan** [devarshishimpi/Elite-Bot#25]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Make a core to the bot that can handle separate folders for buttons, select menus, models, ETC.

**Describe alternatives you've considered**
none since we need collections for each interaction type so handling via the interactionCreate event wont work 

**Additional context**
![image](https://user-images.githubusercontent.com/80361877/195469629-7a225692-5c53-4381-bf89-01abdd9da1f4.png)
This is the type of system the bot would use.  This is the system I use on my bot.

[Github link to my bot that uses this system](https://github.com/Mini51/Personal-bot) 

If you do decide you want this system let me know

**Comment by TheDeveloperRyan** [comment]
I dont mind refactoring the bot again lol =)

**Comment by devarshishimpi** [comment]
Great!
