### ISSUE TITLE
Should update to v14 of Discord.JS  

### ISSUE THREAD

**Issue by TheDeveloperRyan** [devarshishimpi/Elite-Bot#7]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Updating to slash command with Discord.JS v14  due to message intent becoming a Privileged Intent

**Describe alternatives you've considered**
None 

**Additional context**
None

**Comment by devarshishimpi** [comment]
@Mini51 Hey,

Thanks for the updates, We can continue the discussion on Discord itself where development is in progress.
lil.dev#0383

**Comment by lilmistake** [comment]
I'll be down to work on it :raised_hand_with_fingers_splayed:

**Comment by TheDeveloperRyan** [comment]
Sorry for late response, but I would love to help make the change to V14. @devarshishimpi I will add you on Discord so we can discuss it further

**Comment by devarshishimpi** [comment]
> Sorry for late response, but I would love to help make the change to V14. @devarshishimpi I will add you on Discord so we can discuss it further

@Mini51 Alright 😄
